### PR TITLE
Added very basic vs2015 support

### PR DESCRIPTION
**Pull request by samsinsane**

### CODE REVIEW

**Comment by samsinsane** [comment]
I've noticed a few issues with this that need to be fixed up before merging, this module has a dependency on another module that happened to be loaded when I was generating the projects (oops). I'll also split this out into multiple files, `vsandroid_vstudio.lua`, `vsandroid_sln2005.lua` and `vsandroid_androidproj.lua`. This should make it consistent with premake-core, as well as making it easier to extend and understand.

**Comment by samsinsane** [comment]
@TurkeyMan I've split this up into multiple files and fixed a couple of issues with it. Let me know if there's any issues.

**Comment by TurkeyMan** [comment]
I finally tried it out, works as advertised :)
I'm thinking the old 3rd party solution stuff can safely be stripped out now MS have committed to supporting it themselves.

**Comment by samsinsane** [comment]
The MS implementation only works in VS2015+, whereas the vs-android implementation doesn't work with VS2015+, just VS2010-2013. I think it still has a purpose, but I guess it depends on how much use it gets.

**Comment by TurkeyMan** [comment]
True, but I'm thinking it's safe to say that anyone doing Android dev with VS will have updated no?
Safe to say that it'll never be tested by either of us...

**Pull request merged**
